/* tslint:disable */
/* eslint-disable */
/**
 * Chatbot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface ChatRequest {
    'message': string;
}
export interface CustomRulesResponse {
    'rules': string | null;
}
export interface CustomRulesUpdateRequest {
    'rules': string;
}
export interface HTTPValidationError {
    'detail'?: Array<ValidationError>;
}
export interface LocationInner {
}
export interface MemoryFactResponse {
    'id': string;
    'content': string;
    'timestamp': string | null;
}
export interface MemoryResponse {
    'facts': Array<MemoryFactResponse>;
}
export interface MessageResponse {
    'message_id': string;
    'role': MessageResponseRoleEnum;
    'content': string;
    'timestamp': string;
}

export const MessageResponseRoleEnum = {
    User: 'user',
    Assistant: 'assistant'
} as const;

export type MessageResponseRoleEnum = typeof MessageResponseRoleEnum[keyof typeof MessageResponseRoleEnum];

export interface PaginatedMessagesResponse {
    'total': number;
    'page': number;
    'limit': number;
    'items': Array<MessageResponse>;
}
export interface PaginatedSessionsResponse {
    'total': number;
    'page': number;
    'limit': number;
    'items': Array<SessionResponse>;
}
export interface SessionCreateRequest {
    'title': string;
}
export interface SessionResponse {
    'session_id': string;
    'title': string;
    'created_at': string;
    'updated_at': string;
}
export interface SessionUpdateRequest {
    'title': string;
}
export interface ValidationError {
    'loc': Array<LocationInner>;
    'msg': string;
    'type': string;
    'input'?: any;
    'ctx'?: object;
}

/**
 * ChatApi - axios parameter creator
 */
export const ChatApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Chat
         * @param {string} sessionId 
         * @param {ChatRequest} chatRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        chatApiV1ChatSessionIdPost: async (sessionId: string, chatRequest: ChatRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sessionId' is not null or undefined
            assertParamExists('chatApiV1ChatSessionIdPost', 'sessionId', sessionId)
            // verify required parameter 'chatRequest' is not null or undefined
            assertParamExists('chatApiV1ChatSessionIdPost', 'chatRequest', chatRequest)
            const localVarPath = `/api/v1/chat/{session_id}`
                .replace(`{${"session_id"}}`, encodeURIComponent(String(sessionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(chatRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ChatApi - functional programming interface
 */
export const ChatApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ChatApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Chat
         * @param {string} sessionId 
         * @param {ChatRequest} chatRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async chatApiV1ChatSessionIdPost(sessionId: string, chatRequest: ChatRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.chatApiV1ChatSessionIdPost(sessionId, chatRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ChatApi.chatApiV1ChatSessionIdPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ChatApi - factory interface
 */
export const ChatApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ChatApiFp(configuration)
    return {
        /**
         * 
         * @summary Chat
         * @param {ChatApiChatApiV1ChatSessionIdPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        chatApiV1ChatSessionIdPost(requestParameters: ChatApiChatApiV1ChatSessionIdPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.chatApiV1ChatSessionIdPost(requestParameters.sessionId, requestParameters.chatRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for chatApiV1ChatSessionIdPost operation in ChatApi.
 */
export interface ChatApiChatApiV1ChatSessionIdPostRequest {
    readonly sessionId: string

    readonly chatRequest: ChatRequest
}

/**
 * ChatApi - object-oriented interface
 */
export class ChatApi extends BaseAPI {
    /**
     * 
     * @summary Chat
     * @param {ChatApiChatApiV1ChatSessionIdPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public chatApiV1ChatSessionIdPost(requestParameters: ChatApiChatApiV1ChatSessionIdPostRequest, options?: RawAxiosRequestConfig) {
        return ChatApiFp(this.configuration).chatApiV1ChatSessionIdPost(requestParameters.sessionId, requestParameters.chatRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * CustomRulesApi - axios parameter creator
 */
export const CustomRulesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Return the authenticated user\'s custom rules string (null if not set).
         * @summary Get Custom Rules
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCustomRulesApiV1CustomRulesGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/custom-rules`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Upsert the authenticated user\'s custom rules string.
         * @summary Update Custom Rules
         * @param {CustomRulesUpdateRequest} customRulesUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCustomRulesApiV1CustomRulesPut: async (customRulesUpdateRequest: CustomRulesUpdateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'customRulesUpdateRequest' is not null or undefined
            assertParamExists('updateCustomRulesApiV1CustomRulesPut', 'customRulesUpdateRequest', customRulesUpdateRequest)
            const localVarPath = `/api/v1/custom-rules`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(customRulesUpdateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CustomRulesApi - functional programming interface
 */
export const CustomRulesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CustomRulesApiAxiosParamCreator(configuration)
    return {
        /**
         * Return the authenticated user\'s custom rules string (null if not set).
         * @summary Get Custom Rules
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCustomRulesApiV1CustomRulesGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CustomRulesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCustomRulesApiV1CustomRulesGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CustomRulesApi.getCustomRulesApiV1CustomRulesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Upsert the authenticated user\'s custom rules string.
         * @summary Update Custom Rules
         * @param {CustomRulesUpdateRequest} customRulesUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateCustomRulesApiV1CustomRulesPut(customRulesUpdateRequest: CustomRulesUpdateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CustomRulesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateCustomRulesApiV1CustomRulesPut(customRulesUpdateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CustomRulesApi.updateCustomRulesApiV1CustomRulesPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CustomRulesApi - factory interface
 */
export const CustomRulesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CustomRulesApiFp(configuration)
    return {
        /**
         * Return the authenticated user\'s custom rules string (null if not set).
         * @summary Get Custom Rules
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCustomRulesApiV1CustomRulesGet(options?: RawAxiosRequestConfig): AxiosPromise<CustomRulesResponse> {
            return localVarFp.getCustomRulesApiV1CustomRulesGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Upsert the authenticated user\'s custom rules string.
         * @summary Update Custom Rules
         * @param {CustomRulesApiUpdateCustomRulesApiV1CustomRulesPutRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCustomRulesApiV1CustomRulesPut(requestParameters: CustomRulesApiUpdateCustomRulesApiV1CustomRulesPutRequest, options?: RawAxiosRequestConfig): AxiosPromise<CustomRulesResponse> {
            return localVarFp.updateCustomRulesApiV1CustomRulesPut(requestParameters.customRulesUpdateRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for updateCustomRulesApiV1CustomRulesPut operation in CustomRulesApi.
 */
export interface CustomRulesApiUpdateCustomRulesApiV1CustomRulesPutRequest {
    readonly customRulesUpdateRequest: CustomRulesUpdateRequest
}

/**
 * CustomRulesApi - object-oriented interface
 */
export class CustomRulesApi extends BaseAPI {
    /**
     * Return the authenticated user\'s custom rules string (null if not set).
     * @summary Get Custom Rules
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCustomRulesApiV1CustomRulesGet(options?: RawAxiosRequestConfig) {
        return CustomRulesApiFp(this.configuration).getCustomRulesApiV1CustomRulesGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Upsert the authenticated user\'s custom rules string.
     * @summary Update Custom Rules
     * @param {CustomRulesApiUpdateCustomRulesApiV1CustomRulesPutRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateCustomRulesApiV1CustomRulesPut(requestParameters: CustomRulesApiUpdateCustomRulesApiV1CustomRulesPutRequest, options?: RawAxiosRequestConfig) {
        return CustomRulesApiFp(this.configuration).updateCustomRulesApiV1CustomRulesPut(requestParameters.customRulesUpdateRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Health
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthHealthGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Health
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthHealthGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthHealthGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.healthHealthGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Health
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthHealthGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.healthHealthGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Health
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public healthHealthGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).healthHealthGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * MemoryApi - axios parameter creator
 */
export const MemoryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Return all stored memory facts for the authenticated user.
         * @summary Get Memory
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMemoryApiV1MemoryGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/memory`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MemoryApi - functional programming interface
 */
export const MemoryApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MemoryApiAxiosParamCreator(configuration)
    return {
        /**
         * Return all stored memory facts for the authenticated user.
         * @summary Get Memory
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMemoryApiV1MemoryGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MemoryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMemoryApiV1MemoryGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MemoryApi.getMemoryApiV1MemoryGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MemoryApi - factory interface
 */
export const MemoryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MemoryApiFp(configuration)
    return {
        /**
         * Return all stored memory facts for the authenticated user.
         * @summary Get Memory
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMemoryApiV1MemoryGet(options?: RawAxiosRequestConfig): AxiosPromise<MemoryResponse> {
            return localVarFp.getMemoryApiV1MemoryGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MemoryApi - object-oriented interface
 */
export class MemoryApi extends BaseAPI {
    /**
     * Return all stored memory facts for the authenticated user.
     * @summary Get Memory
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getMemoryApiV1MemoryGet(options?: RawAxiosRequestConfig) {
        return MemoryApiFp(this.configuration).getMemoryApiV1MemoryGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * SessionsApi - axios parameter creator
 */
export const SessionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Session
         * @param {SessionCreateRequest} sessionCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSessionApiV1SessionsPost: async (sessionCreateRequest: SessionCreateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sessionCreateRequest' is not null or undefined
            assertParamExists('createSessionApiV1SessionsPost', 'sessionCreateRequest', sessionCreateRequest)
            const localVarPath = `/api/v1/sessions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(sessionCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete Session
         * @param {string} sessionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSessionApiV1SessionsSessionIdDelete: async (sessionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sessionId' is not null or undefined
            assertParamExists('deleteSessionApiV1SessionsSessionIdDelete', 'sessionId', sessionId)
            const localVarPath = `/api/v1/sessions/{session_id}`
                .replace(`{${"session_id"}}`, encodeURIComponent(String(sessionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Session
         * @param {string} sessionId 
         * @param {number} [page] Page number (1-based)
         * @param {number} [limit] Messages per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSessionApiV1SessionsSessionIdGet: async (sessionId: string, page?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sessionId' is not null or undefined
            assertParamExists('getSessionApiV1SessionsSessionIdGet', 'sessionId', sessionId)
            const localVarPath = `/api/v1/sessions/{session_id}`
                .replace(`{${"session_id"}}`, encodeURIComponent(String(sessionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List Sessions
         * @param {number} [page] Page number (1-based)
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSessionsApiV1SessionsGet: async (page?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/sessions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update Session
         * @param {string} sessionId 
         * @param {SessionUpdateRequest} sessionUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSessionApiV1SessionsSessionIdPatch: async (sessionId: string, sessionUpdateRequest: SessionUpdateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sessionId' is not null or undefined
            assertParamExists('updateSessionApiV1SessionsSessionIdPatch', 'sessionId', sessionId)
            // verify required parameter 'sessionUpdateRequest' is not null or undefined
            assertParamExists('updateSessionApiV1SessionsSessionIdPatch', 'sessionUpdateRequest', sessionUpdateRequest)
            const localVarPath = `/api/v1/sessions/{session_id}`
                .replace(`{${"session_id"}}`, encodeURIComponent(String(sessionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(sessionUpdateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SessionsApi - functional programming interface
 */
export const SessionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SessionsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create Session
         * @param {SessionCreateRequest} sessionCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createSessionApiV1SessionsPost(sessionCreateRequest: SessionCreateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SessionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createSessionApiV1SessionsPost(sessionCreateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SessionsApi.createSessionApiV1SessionsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete Session
         * @param {string} sessionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteSessionApiV1SessionsSessionIdDelete(sessionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteSessionApiV1SessionsSessionIdDelete(sessionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SessionsApi.deleteSessionApiV1SessionsSessionIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Session
         * @param {string} sessionId 
         * @param {number} [page] Page number (1-based)
         * @param {number} [limit] Messages per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSessionApiV1SessionsSessionIdGet(sessionId: string, page?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedMessagesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSessionApiV1SessionsSessionIdGet(sessionId, page, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SessionsApi.getSessionApiV1SessionsSessionIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List Sessions
         * @param {number} [page] Page number (1-based)
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listSessionsApiV1SessionsGet(page?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedSessionsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listSessionsApiV1SessionsGet(page, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SessionsApi.listSessionsApiV1SessionsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update Session
         * @param {string} sessionId 
         * @param {SessionUpdateRequest} sessionUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateSessionApiV1SessionsSessionIdPatch(sessionId: string, sessionUpdateRequest: SessionUpdateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SessionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateSessionApiV1SessionsSessionIdPatch(sessionId, sessionUpdateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SessionsApi.updateSessionApiV1SessionsSessionIdPatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SessionsApi - factory interface
 */
export const SessionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SessionsApiFp(configuration)
    return {
        /**
         * 
         * @summary Create Session
         * @param {SessionsApiCreateSessionApiV1SessionsPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSessionApiV1SessionsPost(requestParameters: SessionsApiCreateSessionApiV1SessionsPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<SessionResponse> {
            return localVarFp.createSessionApiV1SessionsPost(requestParameters.sessionCreateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete Session
         * @param {SessionsApiDeleteSessionApiV1SessionsSessionIdDeleteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSessionApiV1SessionsSessionIdDelete(requestParameters: SessionsApiDeleteSessionApiV1SessionsSessionIdDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteSessionApiV1SessionsSessionIdDelete(requestParameters.sessionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Session
         * @param {SessionsApiGetSessionApiV1SessionsSessionIdGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSessionApiV1SessionsSessionIdGet(requestParameters: SessionsApiGetSessionApiV1SessionsSessionIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<PaginatedMessagesResponse> {
            return localVarFp.getSessionApiV1SessionsSessionIdGet(requestParameters.sessionId, requestParameters.page, requestParameters.limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List Sessions
         * @param {SessionsApiListSessionsApiV1SessionsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSessionsApiV1SessionsGet(requestParameters: SessionsApiListSessionsApiV1SessionsGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<PaginatedSessionsResponse> {
            return localVarFp.listSessionsApiV1SessionsGet(requestParameters.page, requestParameters.limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update Session
         * @param {SessionsApiUpdateSessionApiV1SessionsSessionIdPatchRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSessionApiV1SessionsSessionIdPatch(requestParameters: SessionsApiUpdateSessionApiV1SessionsSessionIdPatchRequest, options?: RawAxiosRequestConfig): AxiosPromise<SessionResponse> {
            return localVarFp.updateSessionApiV1SessionsSessionIdPatch(requestParameters.sessionId, requestParameters.sessionUpdateRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createSessionApiV1SessionsPost operation in SessionsApi.
 */
export interface SessionsApiCreateSessionApiV1SessionsPostRequest {
    readonly sessionCreateRequest: SessionCreateRequest
}

/**
 * Request parameters for deleteSessionApiV1SessionsSessionIdDelete operation in SessionsApi.
 */
export interface SessionsApiDeleteSessionApiV1SessionsSessionIdDeleteRequest {
    readonly sessionId: string
}

/**
 * Request parameters for getSessionApiV1SessionsSessionIdGet operation in SessionsApi.
 */
export interface SessionsApiGetSessionApiV1SessionsSessionIdGetRequest {
    readonly sessionId: string

    /**
     * Page number (1-based)
     */
    readonly page?: number

    /**
     * Messages per page
     */
    readonly limit?: number
}

/**
 * Request parameters for listSessionsApiV1SessionsGet operation in SessionsApi.
 */
export interface SessionsApiListSessionsApiV1SessionsGetRequest {
    /**
     * Page number (1-based)
     */
    readonly page?: number

    /**
     * Items per page
     */
    readonly limit?: number
}

/**
 * Request parameters for updateSessionApiV1SessionsSessionIdPatch operation in SessionsApi.
 */
export interface SessionsApiUpdateSessionApiV1SessionsSessionIdPatchRequest {
    readonly sessionId: string

    readonly sessionUpdateRequest: SessionUpdateRequest
}

/**
 * SessionsApi - object-oriented interface
 */
export class SessionsApi extends BaseAPI {
    /**
     * 
     * @summary Create Session
     * @param {SessionsApiCreateSessionApiV1SessionsPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createSessionApiV1SessionsPost(requestParameters: SessionsApiCreateSessionApiV1SessionsPostRequest, options?: RawAxiosRequestConfig) {
        return SessionsApiFp(this.configuration).createSessionApiV1SessionsPost(requestParameters.sessionCreateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete Session
     * @param {SessionsApiDeleteSessionApiV1SessionsSessionIdDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteSessionApiV1SessionsSessionIdDelete(requestParameters: SessionsApiDeleteSessionApiV1SessionsSessionIdDeleteRequest, options?: RawAxiosRequestConfig) {
        return SessionsApiFp(this.configuration).deleteSessionApiV1SessionsSessionIdDelete(requestParameters.sessionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Session
     * @param {SessionsApiGetSessionApiV1SessionsSessionIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getSessionApiV1SessionsSessionIdGet(requestParameters: SessionsApiGetSessionApiV1SessionsSessionIdGetRequest, options?: RawAxiosRequestConfig) {
        return SessionsApiFp(this.configuration).getSessionApiV1SessionsSessionIdGet(requestParameters.sessionId, requestParameters.page, requestParameters.limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List Sessions
     * @param {SessionsApiListSessionsApiV1SessionsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listSessionsApiV1SessionsGet(requestParameters: SessionsApiListSessionsApiV1SessionsGetRequest = {}, options?: RawAxiosRequestConfig) {
        return SessionsApiFp(this.configuration).listSessionsApiV1SessionsGet(requestParameters.page, requestParameters.limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update Session
     * @param {SessionsApiUpdateSessionApiV1SessionsSessionIdPatchRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateSessionApiV1SessionsSessionIdPatch(requestParameters: SessionsApiUpdateSessionApiV1SessionsSessionIdPatchRequest, options?: RawAxiosRequestConfig) {
        return SessionsApiFp(this.configuration).updateSessionApiV1SessionsSessionIdPatch(requestParameters.sessionId, requestParameters.sessionUpdateRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



